# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xci
# IP: The module: 'clk_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: G:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.srcs/sources_1/ip/clk_65mhz/clk_65mhz.xci
# IP: The module: 'clk_65mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/My Drive/FPGA_Development/spartan7_vga_display/spartan7_vga_display.gen/sources_1/ip/clk_65mhz/clk_65mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_65mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
